.SUFFIXES: .obj .c .asm .lst

CL = \c51\binp\cl
CFLAGS = -W3 -c -Alfu /NT_TEXT -G2s -Zl -Zp -O -nologo
INC = \ddkx86\inc
CINC = \c51\include
H = \ddkx86\h
LINK = \ddkx86\tools\link
LFLAGS = /MAP /NOI /NOE /nod /exepack /packd /a:16 /far
MASM = masm
MFLAGS =  -MX -T -N
MAPSYM = mapsym
CLIB=\C51\lib
DDKLIB=\ddkx86\lib
LIBS=$(DDKLIB)\os2286.lib $(DDKLIB)\os2286p.lib $(CLIB)\LLIBCE.LIB
INCLUDE=.;$(INC);$(H);$(CINC)
LIB=$(CLIB);$(DDKLIB)

TARGET=xf86sup.sys
OBJS=dvasm.obj conidc.obj dvdata.obj io.obj map.obj ttypty.obj \
     cons.obj util.obj dvinit.obj
DEF=xf86sup.def

all:	version $(TARGET)

dvinit.obj: version.h dvinit.c

conidc.obj: ..\api\conidc.asm
	$(MASM) $(MFLAGS) ..\api\conidc.asm,conidc.obj;

version:
	@newvers

clean:
	if exist *.obj del *.obj
	if exist *.sys del *.sys
	if exist *.sym del *.sym
	if exist *.lst del *.lst
	if exist *.map del *.map

.asm.obj:
	$(MASM) $(MFLAGS) $*.asm;

.c.obj:
	$(CL) $(CFLAGS) $(CINC) $*.c

.c.lst:
	$(CL) $(CFLAGS) /Fc $(CINC) $*.c
	copy $*.cod $*.lst
	del $*.cod

$(TARGET): $(OBJS) $(LIBS) $(DEF) makefile
	$(LINK) $(LFLAGS) $(OBJS),$(TARGET),,$(LIBS),xf86sup.def
	$(MAPSYM) xf86sup.map
	copy $(TARGET) ..
	copy xf86sup.sym ..
